### ISSUE TITLE
Enhance Meteor client not to reload the scripts that were already in the previous page

### ISSUE THREAD

**Issue by antoninadert** [meteor/meteor-feature-requests#181]
### Isobuild is doing a bad job when used alongside a client router
- [ ]  It refreshes all the scripts of my client page on route change, but only a few scripts/imports were missing from the previous page, so no need to refresh everything (takes frames on screen).
- [ ] Current fix: Disabling javascript in the Browser will greatly improve the DomContentLoaded time.
- [ ] Proposed Solution: When a page-change, page-refresh, page-submit (etc.) event occurs, Meteor should be able to only rebuild the HTML that is missing and preserve the scripts.

Technical solution ': 
- [ ] Using a virtual DOM to make the diffing
- [ ] Hack the system in some way

This is probably a solution in isobuild but maybe not only.
For a repro of current behavior install [my universal-router prototype](https://github.com/antoninadert/proto-starter) and try to disable javascript with Quick Javascript Switcher chrome extension, and open chrome inspector.
Changing routes (for example try /about and /anything) will result in longer page transition if javascript is enabled.

You will notice the DomContentLoaded time difference when changing routes and pressing back and forth buttons, if you use javascript or not, even if only a few scripts differ. 

Once the page caches the content, it will actually be faster for the next steps, but this does not solve the problem.

**Comment by antoninadert** [comment]
Maybe related to #24 where javascript order would be important in the page loading time (client-side).

**Comment by klaussner** [comment]
The problem here is that you are not really using the client-side router. If you click on a link, the browser simply navigates to the `href` URL as if it were a link on a "traditional", non-SPA website (the browser doesn't know that you want to do client-side routing). What you need to do is listen to the `onClick` event on your links, prevent the default behavior of the browser, and change the browser `history`, which will trigger the `history.listen` handler and render the component without reloading the page.

Here is a full example for `universal-router`: https://github.com/kriasoft/universal-router/issues/80#issuecomment-281077903
