### ISSUE TITLE
Use a service worker to load javascript

### ISSUE THREAD

**Issue by antoninadert** [meteor/meteor-feature-requests#184]
### How to focus the UI thread on rendering HTML+CSS, while javascript will load in another background thread ? 

I want to have fastest time to first-paint, but the javascript parse and compile time can be huge.
- Maybe a Service Worker can solve this issue ?

I realized that my app passes Google lighthouse audit way better if javascript is disabled.

This is probably because no additional resource is consuming my time to render, time to first-consistently-interactive state, with UI thread idle (javascript initialization)

An hybrid approach would be to delegate javascript to a second thread.
This could speed up load times

**Comment by benjamn** [comment]
Here's my current take on why Service Workers are (still) a bad idea for Meteor: https://twitter.com/benjamn/status/872510575850475520

Have you tried [dynamic `import()`](https://blog.meteor.com/announcing-meteor-1-5-b82be66571bb)? It allows you to decide when to load additional JavaScript, and anything you've previously loaded will be permanently cached in IndexedDB. Service Workers are not involved in that process (in Meteor), though some other projects use Service Workers for code splitting and dynamic `import()`.

Browsers are able to fetch JavaScript and other resources over the network using any technique they choose, so workers probably won't help speed up those HTTP requests.

Ultimately any JavaScript that's involved in displaying your app has to get evaluated in the `window` environment (not in a worker), which is single-threaded because that's how JavaScript works. I'm not sure I see much opportunity for workers to speed up that process. JavaScript is critical to Meteor apps, plain and simple.

I'm going to close this issue because I don't think there's an actionable feature request here, but please feel free to keep thinking about this problem, and reopen the issue if you can provide more concrete details about how this could work.
