### ISSUE TITLE
Run meteor npm install if node_modules is not present

### ISSUE THREAD

**Issue by juho** [meteor/meteor-feature-requests#202]
Would be nice if running `meteor` checks if `./node_modules/` exists, and if not run `meteor npm install` first like it does for Meteor packages. I get burnt by this every time with a repo pull. I can't be the only one.. :)

**Comment by hwillson** [comment]
You're not the only one @juho - see https://github.com/meteor/meteor/issues/6848. This is now done automatically when creating new apps, but not automatically when running old apps. This is by design - Meteor can't make assumptions about your existing `node_modules` workflow (e.g. maybe the app is using `yarn`). For more details about this, see PR https://github.com/meteor/meteor/pull/8108.

**Comment by juho** [comment]
Ah cool, didn't bump into that in search. Thanks!
