### ISSUE TITLE
Add way to explicitly install Windows meteor to non-administrator user

### ISSUE THREAD

**Issue by brucejo75** [meteor/meteor-feature-requests#214]
### The Problem
Want to install Windows meteor to a non system administrator account.

chocolately install is great.  But it only installs to system administrator account.  😕

There is a workaround, see [meteor #9288](https://github.com/meteor/meteor/issues/9288)
Essentially, change a couple of environment variables:
```
set LOCALAPPDATA=C:\Users\<USERNAME>\AppData\Local
set USERPROFILE=C:\Users\<USERNAME>
```
The workaround is a little hacky and could one day have side effects (does not seem to today).

### Recommendation
Add override environment variable that the install script will read and will explicitly install to.  For example,

```
METEOR_INSTALL_PROFILE=C:\Users\<USERNAME>\AppData\Local
```
or
```
METEOR_INSTALL_USER=<USERNAME>
```

**Comment by abernix** [comment]
I don't think it makes sense to have this as a feature request at the moment since this is the expected behavior and if that's not happening, we'll need to get to the bottom of that.  As I mentioned in the issue, this is working for me right now with Windows, so we should try to figure out what's wrong with that first.
