### ISSUE TITLE
Update mongodb driver to v3

### ISSUE THREAD

**Issue by gustawdaniel** [meteor/meteor-feature-requests#268]
## What could we do?

I propose to update `mongodb: "2.2.33"` to `mongodb: "3.0.2"` in `packages/npm-mongo/package.js`.

## Why?

I wanted to use `The filtered positional operator` described in docs of mongodb on this page:

> https://docs.mongodb.com/manual/reference/operator/update/positional-filtered/

It works only for newest mongodb driver. Article about this in under link:

> http://thecodebarbarian.com/a-nodejs-perspective-on-mongodb-36-array-filters.html

In this article there is written:

> Using array filters with Node.js requires versions >= 3.0.0 of the MongoDB Node.js driver or >= 5.0.0 of mongoose in addition to v3.6 of the MongoDB server. Earlier versions of the MongoDB (2.x) and mongoose (4.x) do not support array filters.

## Overview of the suggested solution

Simple change of version is not enough. @hwillson described this problem in this closed pull request:

> https://github.com/meteor/meteor/pull/9670

I do not know details mentioned by him, but I am interested in any help.

**Comment by klaussner** [comment]
Here's a summary of the required changes I found while going through the [`node-mongodb-native` `CHANGES_3.0.0.md` document](
https://github.com/mongodb/node-mongodb-native/blob/3.0.0/CHANGES_3.0.0.md):

**Connection**

`MongoClient.connect` passes the client instead of a database object to the callback function. This means that the driver doesn't create a `Db` instance from the database URL (e.g., `mongodb://localhost:3001/meteor`) anymore, so we have to create the `Db` instance in [the callback](https://github.com/meteor/meteor/blob/5e9ff342a8ce9e488e2af4086d39ac1e73325e9c/packages/mongo/mongo_driver.js#L173):

```js
function (err, client) {
  // ...
  const db = client.db("meteor");
  
  if (db.server.config.isMasterDoc) {
  // ...
```

Of course, the database name isn't always `meteor`, so we have to either parse the URL ourselves or use the (undocumented) `client.s.options.dbName` property to get the database name.

**Removed functions**

* `Cursor.prototype.next` must be used instead of `Cursor.prototype.nextObject` ([here](https://github.com/meteor/meteor/blob/5e9ff342a8ce9e488e2af4086d39ac1e73325e9c/packages/mongo/mongo_driver.js#L1008)).
* `MongoClient.prototype.close` must be used instead of `Db.prototype.close` ([here](https://github.com/meteor/meteor/blob/5e9ff342a8ce9e488e2af4086d39ac1e73325e9c/packages/mongo/mongo_driver.js#L234)). 

**Renamed option**

* As @hwillson mentioned in https://github.com/meteor/meteor/pull/9670#issuecomment-366015290, the `fields` option of `find` has been renamed to `projection`. Would [`MongoConnection.prototype.find`](https://github.com/meteor/meteor/blob/5e9ff342a8ce9e488e2af4086d39ac1e73325e9c/packages/mongo/mongo_driver.js#L765-L773) be the right place to make this change?

**Comment by benan789** [comment]
Using arrayFilters is working with rawCollection but not through meteor. Will this be added soon?

**Comment by dobesv** [comment]
BTW I believe if you call `client.db()` with no parameter it'll use the `dbName` from the connection URL.

**Comment by klaussner** [comment]
@dobesv This feature was added to `node-mongodb-native` shortly after I created the first pull request (meteor/meteor#9790). I changed the constructor to use `client.db()` in meteor/meteor#9831. 🙂

**Comment by klaussner** [comment]
The driver has been updated in Meteor 1.7.

**Comment by lamalex** [comment]
On Meteor 1.7.0.5 and 
`Journal.Totals.update(
    { $and: c.q },
    { $inc: { [identifier]: nutrient.value } },
    { arrayFilters: [ { 't.providerData.internalID': nutrient.providerData.internalID } ] }
);`
fails whereas
`Journal.Totals.rawCollection().update(
    { $and: c.q },
    { $inc: { [identifier]: nutrient.value } },
    { arrayFilters: [ { 't.providerData.internalID': nutrient.providerData.internalID } ] }
);`
passes.

**Comment by mitar** [comment]
What is the error? Does it fail on Minimongo?
