### ISSUE TITLE
Consider a community code of conduct

### ISSUE THREAD

**Issue by dhrubins** [meteor/meteor-feature-requests#65]
I recently noticed there doesn't seem to be a community code of conduct or community guidelines for Meteor, beyond what's in the contribution guidelines. The contribution guidelines seem more... mechanical, like *how* to contribute, descriptions of team roles, processes, etc.

Open source communities really thrive when they are welcoming, diverse, and collaborative. Here are some examples of existing community guidelines and codes of conduct from other OSS groups: [twitter/code-of-conduct](https://github.com/twitter/code-of-conduct) and [todogroup/opencodeofconduct](https://github.com/todogroup/opencodeofconduct).

@theadactyl - as the community manager, I think it would be great to get your input on this!

**Comment by theadactyl** [comment]
I thought we had one similar to the one we have for Apollo - if not, I will
add it in ASAP. Thanks for the heads up!

**Comment by hwillson** [comment]
One small suggestion - I find the Apollo code of conduct to be a bit buried. I know it can be found pretty easily on the web since it’s part of the [Apollo community site](http://dev.apollodata.com/community/code-of-conduct.html), but when looking for it directly in GitHub, it’s a bit [tricky to find](https://github.com/apollographql/community/blob/master/source/code-of-conduct.md). When we add it to `meteor/meteor`, can it be added directly into the project root, as something like `CODE_OF_CONDUCT.md`?

**Comment by mitar** [comment]
And/or link it from contributing guide, like Django has: https://github.com/django/django/blob/master/CONTRIBUTING.rst#code-of-conduct

(And contributing link is on top of new issue form.)

**Comment by dhrubins** [comment]
I see a code of conduct linked from [meteor.com/policy](https://www.meteor.com/policy), though it looks like it's more targeted toward employees and event attendees.

**Comment by theadactyl** [comment]
Added one based on the existing Code of Conduct for Apollo, which we've been happy with: https://github.com/meteor/meteor/blob/devel/code-of-conduct.md

Hope this works for everyone!

**Comment by hwillson** [comment]
Awesome - thanks @theadactyl!
